version: '3.9'

services:
  ###> Nginx ###
  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./www:/var/www/html
    networks:
      - redlira
    ports:
      - "4200:4200"

  ###< Nginx ###

  ###> Php ###
  php:
    container_name: php-8.0
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - redlira
    volumes:
      - ./app:/var/www/backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    ###< Php ###


    ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:latest
    container_name: mysql
    networks:
      - redlira
    environment:
      - MYSQL_ROOT_PASSWORD=liraFlorida2022
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    ###< doctrine/doctrine-bundle ###

    ###> PhpMyAdmin ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - redlira
    environment:
      - PMA_HOST=database
      - MYSQL_ROOT_PASSWORD=liraFlorida2022
      - PMA_PORT=3306
    ports:
      - "8081:8081"
  ###< PHpMyAdmin ###

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
    ###< doctrine/doctrine-bundle ###

networks:
  redlira:
    driver: bridge
