# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [test]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the stack
        run: docker-compose -f "docker-compose.yml" up -d
      - name: Build
        run: |
          docker-compose -f "docker-compose.yml" build
      - name: Push from Docker
        run: |
          composeServices = readYaml('docker-compose.yaml').services
          image1 = composeServices.nginx.image
          image2 = composeServices.php.build
          image3 = composeServices.database.image
          image4 = composeServices.phpmyadmin.image
          docker push image1 image2 image3 image4